name: Frontend CI

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.16
        uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - name: Frontend Install Dependencies
        run: npm install
        working-directory: poker-frontend
      - name: Frontend Build
        run: npm run build
        working-directory: poker-frontend
